name: CI
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Test Hello World Actions SFV-intel-world-open
        uses: dosuken123/github-action-test@main
        with:
          # Who to greet
          who-to-greet: dosuken
